"""add reservations

Revision ID: 762ecf436cef
Revises: 82da33d29892
Create Date: 2026-08-20 15:43:31.991624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '762ecf436cef'
down_revision = '82da33d29892'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reservations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tool_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=32), server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('end_date >= start_date', name='ck_reservations_date_range'),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(
        'ix_reservations_tool_status_dates',
        'reservations',
        ['tool_id', 'status', 'start_date', 'end_date'],
        unique=False,
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_reservations_tool_status_dates', table_name='reservations')

    op.drop_table('reservations')
    # ### end Alembic commands ###
