"""create tools catalog tables

Revision ID: 82da33d29892
Revises: 
Create Date: 2026-08-18 15:17:32.914361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82da33d29892'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('daily_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('deposit_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('pickup_available', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('delivery_available', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('delivery_price_per_km', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_published', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_available', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('included_km', sa.Integer(), nullable=True),
    sa.Column('extra_km_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('daily_price >= 0', name='ck_tools_daily_price_non_negative'),
    sa.CheckConstraint('delivery_price_per_km >= 0', name='ck_tools_delivery_price_per_km_non_negative'),
    sa.CheckConstraint('deposit_amount >= 0', name='ck_tools_deposit_amount_non_negative'),
    sa.CheckConstraint('extra_km_price >= 0', name='ck_tools_extra_km_price_non_negative'),
    sa.CheckConstraint('included_km >= 0', name='ck_tools_included_km_non_negative'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tool_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tool_id', sa.Integer(), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('position >= 0', name='ck_tool_images_position_non_negative'),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tool_id', 'position', name='uq_tool_images_tool_id_position')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tool_images')
    op.drop_table('tools')
    # ### end Alembic commands ###
